name: kanban-flow
volumes:
  pgdata:
networks:
  public_network:
  db_network:
  smtp_network:
  redis_network:
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - public_network
      - db_network
      - smtp_network
      - redis_network
    depends_on:
      - db
      - smtp
      - redis
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - public_network
      - db_network
    depends_on:
      - db
  smtp:
    image: mailhog/mailhog
    networks:
      - smtp_network
    ports:
      - 8025:8025
  redis:
    image: redis:8.4
    networks:
      - redis_network
  redis_insight:
    image: redis/redisinsight
    networks:
      - redis_network
    environment:
      RI_REDIS_HOST: redis
    ports:
      - 5540:5540
